name: Scheduled Fetch Members and Divisions

on:
  schedule:
    # Run every day at 6am AEDT / 7pm UTC 
    - cron: '0 19 * * *'
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests python-dotenv
    
    - name: Run fetch_divisions
      run: python scripts/fetch_divisions.py
      env:
        TVFY_API_KEY: ${{ secrets.TVFY_API_KEY }}
    
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/parliament/divisions.json
        git commit -m "Update divisions data"
        # The step below is just to ensure that the action doesn't fail if there are no changes to commit
        git diff --quiet && git diff --staged --quiet || (git commit -am "Automate updates"; git push)
        
    - name: Push changes
      run: git push
