[theme]

base="dark"

# Primary accent for interactive elements
#primaryColor="#4037A7"

# Background color for the main content area
#backgroundColor='#1A189C'

# Color used for almost all text
#textColor='#FFFFFF'

#secondaryBackgroundColor='#000395'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif" 

[server]
# Automatically rerun script when the file is modified on disk.
runOnSave = true